### PR TITLE
OZ-450: Updated Quick Start and added implementer guide placeholder.

### PR DESCRIPTION
**Pull request by rbuisson**
https://mekomsolutions.atlassian.net/browse/OZ-450

Quick start guide is made of 3 tabs to run Ozone:
- Online Demo
- Locally (Option with Traefik has been removed - should probably be detailed in a more advanced guide)
- Gitpod

Indicate work in progress status of the Implementation Guide.

⚠️ A bug in the left menu when using titles in tabs.

https://github.com/ozone-his/ozone-docs/assets/10692811/5c91c225-6417-4ef0-ae00-fbd85e5475d6

### CODE REVIEW

**Review by mks-d — CHANGES_REQUESTED** [review]
Mmm, not so sure about referencing the online demo as part of the quick start options to run Ozone FOSS.
The idea of the quick start is to be an "almost zero click install" for integrators.

Accessing the demo, if anything, should be in the users guide somewhere.

**Review by mks-d — CHANGES_REQUESTED** [review]
There is another issue, you can't use the tabs and the titles in the page the way you did it. Because the table of contents on the right has merged all titles in one place, thereby repeating items like 'Run' and 'Browse' because they are part of both the Local and Gitpod options.

**Review by mks-d — CHANGES_REQUESTED** [review]
Ok after looking at this a bit longer than 5 min here is what I suggest:

- Remove the reference to the online demo. This will have to go elsewhere with the usual markers that this is for Ozone **Pro**.
- Let's focus on the most compact set of steps to have Ozone **FOSS** up and running and in order to browse it with almost no knowledge and no effort.
- Extra stuff like stopping, destroying, etc isn't part of the Quick Start, it has to go elsewhere in a section that details those further steps.
- Therefore I would do two set of tabs (without necessarily titling them, but we will see in the end) for Run and Browse (I would get rid of Install as it's not worth it in this context and makes the whole writing more complicated).

In the end let's have two sets of Locally/Gitpod tabs, once for running it and one for browsing it. Any other details go on the next page.

**Comment by rbuisson** [comment]
> There is another issue, you can't use the tabs and the titles in the page the way you did it. Because the table of contents on the right has merged all titles in one place, thereby repeating items like 'Run' and 'Browse' because they are part of both the Local and Gitpod options.

Yes I know. See my comment in JIRA:
> Note that there seem to be a bug in MkDocs that makes the left menu to misbehave when there is titles within tabs. See at the end of the video attached in the PR.

**Comment by rbuisson** [comment]
> Mmm, not so sure about referencing the online demo as part of the quick start options to run Ozone FOSS. The idea of the quick start is to be an "almost zero click install" for integrators.
> 
> Accessing the demo, if anything, should be in the users guide somewhere.

OK I guess it makes sense that it's in the User Guide.
Thing is I would have liked this information to stand out clearly. So that anyone can check out the docs to get the Ozone Demo link.
I feel it's more important than any other information.

**Comment by rbuisson** [comment]
>Extra stuff like stopping, destroying, etc isn't part of the Quick Start, it has to go elsewhere in a section that details those further steps.

I've put this at the bottom of the section, but I think that's quite important too. It happens sometimes that people try the system and then don't know how to stop it after, therefore:
- making their computer very slow
- messing up further troubleshooting as they may not have downed or stopped the system in between.

That sounds only fair to indicate how to stop/destroy it. Especially because it's so easy to do.

**Comment by rbuisson** [comment]
>Therefore I would do two set of tabs (without necessarily titling them, but we will see in the end) for Run and Browse (I would get rid of Install as it's not worth it in this context and makes the whole writing more complicated).
In the end let's have two sets of Locally/Gitpod tabs, once for running it and one for browsing it. Any other details go on the next page.

Would you be able to put together such skeleton so that I can simply drop the instructions there?

**Review by mks-d — COMMENTED** [review]
>I also don't want people to think that they must install Ozone in order to try it. That's why to me the first option is pretty much: "did you try the demo?"

Yes, but it's not an implementer's Quick Start option like the other two. I'll figure out how to bring folks attention to it with some kind of "Did you know?" [admonition](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) positioned at the right place. Also the online demo is Ozone Pro, the Quick Start is for Ozone FOSS.

As for destroy, etc, yes it's easy but it's out of scope anyway, the Quick Start is about guiding how to install, run and browse it super quick. Show the integrators out there that it's almost a zero click process. Of course it's not entirely true and the rest is "implementation details" for later, so, for elsewhere in the docs.

As a general matter of fact it's totally ok to put a lot of stuff in the docs, it will in general be the golden rule, just precisely not on that one special page.

**Review by mks-d — APPROVED** [review]

**Pull request merged**
